Implement base APIs and generate_dump

diff --git a/scripts/generate_dump b/scripts/generate_dump
--- a/scripts/generate_dump
+++ b/scripts/generate_dump
@@ -1152,6 +1152,7 @@ save_platform_info() {
     trap 'handle_error $? $LINENO' ERR
     PLATFORM=${PLATFORM:-`sonic-cfggen -H -v DEVICE_METADATA.localhost.platform`}
     if [[ ! $PLATFORM =~ .*(mlnx|nvidia).*simx.* ]]; then
+        # TODO(BMC): add BMCeeprom if BMC is supported ?
         save_cmd "show platform syseeprom" "syseeprom"
         save_cmd "show platform psustatus" "psustatus"
         save_cmd "show platform ssdhealth --vendor" "ssdhealth"
@@ -1941,6 +1942,88 @@ save_log_files() {
 }
 
 ###############################################################################
+# Check BMC presence
+# Globals:
+#  TAR, TARFILE, DUMPDIR, BASE, TARDIR, TECHSUPPORT_TIME_INFO
+# Arguments:
+#  None
+# Returns:
+#  None
+###############################################################################
+is_bmc_supported() {
+    local platform=$(python3 -c "from sonic_py_common import device_info; print(device_info.get_platform())")
+    # Check if the required file exists
+    if [ ! -f /usr/share/sonic/device/$platform/bmc.json ]; then
+        return 1
+    else
+        return 0
+    fi
+}
+
+###############################################################################
+# Trigger BMC debug log dump task
+# Globals:
+#  TAR, TARFILE, DUMPDIR, BASE, TARDIR, TECHSUPPORT_TIME_INFO
+# Arguments:
+#  None
+# Returns:
+#  None
+###############################################################################
+trigger_bmc_debug_log_dump() {
+    trap 'handle_error $? $LINENO' ERR
+
+    if ! is_bmc_supported; then
+        return
+    fi
+
+    # This script will trigger BMC redfish API start BMC debug log dump task
+    local task_id=$(python3 /usr/local/bin/bmc_techsupport.py -m t)
+    echo $task_id
+}
+
+###############################################################################
+# Save BMC debug log dump files
+# Globals:
+#  TAR, TARFILE, DUMPDIR, BASE, TARDIR, TECHSUPPORT_TIME_INFO
+# Arguments:
+#  None
+# Returns:
+#  None
+###############################################################################
+collect_bmc_files() {
+    $MKDIR $V -p $TARDIR/bmc
+    trap 'handle_error $? $LINENO' ERR
+    start_t=$(date +%s%3N)
+
+    if ! is_bmc_supported; then
+        echo "INFO: BMC is not found on this platform. Skipping..."
+        return
+    fi
+
+    local bmc_debug_log_dump_task_id=$1
+    # Define the tmp filepath of BMC debug log dump
+    local TARBALL_XZ="/tmp/bmc_debug_log_dump.tar.xz"
+
+    # Remove existing tarball files if they exist
+    [ -f "$TARBALL_XZ" ] && rm -f "$TARBALL_XZ"
+
+    # This script will invoke BMC redfish API to extract BMC debug log dump
+    # to "/tmp/bmc_debug_log_dump.tar.xz"
+    python3 /usr/local/bin/bmc_techsupport.py -m c -p "$TARBALL_XZ" -t $bmc_debug_log_dump_task_id
+    if [ -f "$TARBALL_XZ" ]; then
+        $CP $V -rf "$TARBALL_XZ" $TARDIR/bmc
+    else
+        echo "ERROR: File $TARBALL_XZ does not exist."
+    fi
+
+    # Cleanup
+    [ -f "$TARBALL_XZ" ] && rm -f "$TARBALL_XZ"
+
+    end_t=$(date +%s%3N)
+    echo "[ TAR /var/bmc Files ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
+}
+
+###############################################################################
 # Save warmboot files
 # Globals:
 #  TARDIR, TARFILE, TAR, DUMPDIR, TECHSUPPORT_TIME_INFO, NOOP
@@ -2166,6 +2249,12 @@ main() {
     echo $BASE > $TECHSUPPORT_TIME_INFO
     start_t=$(date +%s%3N)
 
+    # Trigger BMC debug log dump task - Must be the first task to run
+    bmc_debug_log_dump_task_id=$(trigger_bmc_debug_log_dump)
+    if [ "$bmc_debug_log_dump_task_id" == "-1" ]; then
+        echo "INFO: Fail to trigger BMC debug log dump. Skipping..."
+    fi
+
     # Capture /proc state early
     save_proc /proc/buddyinfo /proc/cmdline /proc/consoles \
         /proc/cpuinfo /proc/devices /proc/diskstats /proc/dma \
@@ -2379,6 +2468,12 @@ main() {
     save_log_files &
     save_crash_files &
     save_warmboot_files &
+
+    if [ "$bmc_debug_log_dump_task_id" != "-1" ]; then
+        # keep BMC files collect before 'save_to_tar'
+        collect_bmc_files $bmc_debug_log_dump_task_id &
+    fi
+
     wait
 
     save_to_tar
